### ISSUE TITLE
Publish 0.2.10

### ISSUE THREAD

**Issue by TayHobbs** [hooktstudios/capistrano-s3#19]
When I try to pull in the latest version I get  0.2.9 which gives a `uninitialized constant Capistrano::S3 (NameError)` has the latest version been published and I'm missing it, or does the latest version just need a push?

**Comment by j15e** [comment]
Fixed. 

I indeed never published v0.2.10, I think I lost my private signing key at that time. Made a new one.

**Comment by j15e** [comment]
*I published a new v0.2.11 to avoid confusion.
