### ISSUE TITLE
Update AWS SDK gem

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [hooktstudios/capistrano-s3#25]

**Comment by exoszajzbuk** [comment]
@aleksandrs-ledovskis @j15e I have a feature for it along with a rake task which will wait for a CF invalidation to complete. I'll open a PR after #30 is merged and you can decide if you want to release a new major version (there is a breaking change in endpoint config for aws-sdk v2)

**Comment by j15e** [comment]
Great! I will review that PR

**Comment by exoszajzbuk** [comment]
Submitted #32 which includes the AWS SDK update.

**Comment by exoszajzbuk** [comment]
Solved with #32 and updated to `~> 2.6`.
