### ISSUE TITLE
AwsInvalidArgument

### ISSUE THREAD

**Issue by joshuaostrom** [hooktstudios/capistrano-s3#37]
Existing projects using capistrano-s3 have been running great.  Started a new one (with the latest gem) and raninto an error on deploy:
Aws::S3::Errors::InvalidArgument 

The default acl was tripping up S3:
:acl => 'public_read'

Found I *had* to declare 'public-read' to prevent the S3 exception.
set :bucket_write_options, { :acl => 'public-read' }

Looks like the V2 of the aws-sdk was pulled down (new project, I assume aws-sdk (2.8.7) is not compatible with public_read

**Comment by j15e** [comment]
You mean its not compatible with the symbol version anymore? 

I guess we should update the default here https://github.com/hooktstudios/capistrano-s3/blob/master/lib/capistrano/s3/defaults.rb#L6 or set it depending on the AWS sdk version.

**Comment by ddubau** [comment]
I had this same issue with a new project. @joshuaostrom fix resolved the issue by either using set :bucket_write_options, { :acl => 'public-read' } in the deploy config or by modifying the gem code itself to use :acl => 'public-read'. Not sure why this is as the gemspec specifies using the version of aws-sdk that should not have this issue. In my limited research it doesn't seem to be a recent change on the aws-sdk side.

**Comment by j15e** [comment]
Fixed in #35
