### ISSUE TITLE
Problem with target_path feature

### ISSUE THREAD

**Issue by j15e** [hooktstudios/capistrano-s3#38]
As mentionned in #35 by @aleksandrs-ledovskis 

> If target_path is "" (empty string), this prepends / to :key and causes all public/* files appear under extra "slash" directory when deploying, breaking sites. I.e. public/foo.bar will be placed in <bucket_name>//foo.bar.

**Comment by j15e** [comment]
I think we should add a private method to `publisher.rb` to deal with prefixing or not `target_path `

**Comment by joebrislin** [comment]
Was the gem at rubygems ever updated to include this fix? If I use the gem downloaded from rubygems, the issue is still occurring where the extra slash is prepended. I cloned a copy of the repo and set the gem's path to use the local copy and it worked correctly.

**Comment by j15e** [comment]
Not it wasn't released to rubygems. Will do.
